# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.version

<module 'numpy.version' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/version.py'>

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
hint(4)

hint: size, itemsize


In [7]:
a = np.zeros((3, 7))
print(a.size*a.itemsize)

168


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
hint(5)

hint: np.info


In [10]:
np.info("add")

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via t

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
a = np.zeros(10)
a[4] = 1

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [13]:
a = np.arange(1, 11)
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
a = np.arange(0, 9).reshape(3, 3)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [16]:
a = np.array([1,2,0,0,4,0])
b = np.nonzero(a)

In [17]:
b

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [19]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [21]:
np.random.random((3,3,3))

array([[[0.60986856, 0.77647692, 0.30339966],
        [0.92236182, 0.87851869, 0.61922926],
        [0.78194151, 0.59832759, 0.408718  ]],

       [[0.84261474, 0.2087454 , 0.2385143 ],
        [0.54798145, 0.24783901, 0.79732395],
        [0.79203546, 0.47454407, 0.39950198]],

       [[0.57135569, 0.72859266, 0.21531137],
        [0.03452412, 0.40800277, 0.73923342],
        [0.0604972 , 0.0277068 , 0.76775237]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [26]:
a = np.random.random((10,10))
minval = a.min()
maxval = a.max()

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [25]:
print(np.random.random(30).mean())

0.4929912824303431


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [3]:
hint(15)

hint: array[1:-1, 1:-1]


In [6]:
answer(15)

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)


In [7]:
a = np.ones((5,5))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [13]:
a = np.ones((5,5), dtype = np.int64)
np.pad(a, 2)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [8]:
hint(16)

hint: np.pad


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [15]:
hint(17)

hint: NaN = not a number, inf = infinity


In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
a = np.zeros((5,5))
for i in range(1,5):
    a[i][i-1] = i
a

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [7]:
np.diag(np.arange(1,5), k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [8]:
a = np.zeros((8,8))
a[::2, ::2] = 1
a[1:8:2, 1:8:2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [9]:
hint(20)

hint: np.unravel_index


In [10]:
np.unravel_index(100, (6,7,8))

(np.int64(1), np.int64(5), np.int64(4))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [18]:
np.tile(np.array([[0, 1],[1, 0]]), (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
a = np.random.random((5,5))
b = (a - a.mean())/a.std()
b

array([[ 1.38112006, -1.24616943, -0.21933206, -0.83271405, -0.48983915],
       [-0.9478306 ,  1.25119581,  1.78999054,  0.29396305,  1.3088312 ],
       [-0.27273874,  0.88532783,  0.23795022, -0.17208718, -0.30718262],
       [-1.02808805,  1.43440973,  1.28305871, -0.71795309, -1.14897405],
       [-1.08085145, -1.02678268, -0.11156565, -1.39397942,  1.13024107]])

In [22]:
hint(22)

hint: (x -mean)/std


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [27]:
answer(23)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
# a = np.random.random((5,3))
# b = np.random.random((3,2))
# c = np.zeros((5,2))
# for i in range(5):
#     for j in range(2):
#         c[i,j] = a[i, ::].dot(b[::, j])
answer(24)

Z = np.matmul(np.ones((5, 3)), np.ones((3, 2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)


In [41]:
a = np.matmul(np.random.random((5,3)), np.random.random((3,2)))
a

array([[0.7265173 , 1.23431865],
       [0.82449659, 1.45556892],
       [0.26381558, 0.44741356],
       [0.55336121, 0.94863071],
       [0.4331615 , 0.73999219]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [35]:
a = np.arange(1, 11)
a[(3 < a) & (a < 8)] = -1*a[(3 < a) & (a < 8)]
a

array([ 1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [38]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [6]:
a = np.array([1, 2, 3, 5, 0, 4])
b = (2 << a >> 2)
b

array([ 1,  2,  4, 16,  0,  8])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [9]:
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_5493/699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [12]:
a = np.arange(-25, 25)/3
a = np.where(a >= 0, np.ceil(a), np.floor(a))
a

array([-9., -8., -8., -8., -7., -7., -7., -6., -6., -6., -5., -5., -5.,
       -4., -4., -4., -3., -3., -3., -2., -2., -2., -1., -1., -1.,  0.,
        1.,  1.,  1.,  2.,  2.,  2.,  3.,  3.,  3.,  4.,  4.,  4.,  5.,
        5.,  5.,  6.,  6.,  6.,  7.,  7.,  7.,  8.,  8.,  8.])

#### 30. How to find common values between two arrays? (★☆☆)

In [17]:
hint(30)

hint: np.intersect1d


In [20]:
a = np.random.randint(0, 10, (10))
b = np.random.randint(0, 10, (10))
same = np.intersect1d(a, b)
print(a, b, same)

[0 8 1 3 8 2 2 0 9 0] [6 1 2 5 9 2 3 4 7 1] [1 2 3 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [21]:
hint(31)

hint: np.seterr, np.errstate


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_5493/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [33]:
today = np.datetime64("today")
yesterday = today - np.timedelta64(1, "D")
tomorrow = today + np.timedelta64(1, "D")
print(yesterday, today, tomorrow)

2026-06-14 2026-06-15 2026-06-16


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [2]:
dates = np.arange("2016-07", "2016-08", dtype = "datetime64[D]")
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [4]:
answer(35)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [6]:
a = np.random.uniform(0, 10, 5)

a1 = np.floor(a)
a2 = np.trunc(a)
a3 = a.astype(np.int64)
a4 = a - (a % 1)

print(a1, a2, a3, a4)

[3. 2. 1. 8. 0.] [3. 2. 1. 8. 0.] [3 2 1 8 0] [3. 2. 1. 8. 0.]


In [7]:
hint(36)

hint: %, np.floor, astype, np.trunc


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [37]:
a = np.zeros((5,5))
a += np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [2]:
answer(38)

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [6]:
a = np.linspace(0, 1, 11, endpoint = False)[1:]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [46]:
a = np.random.random(10)
a.sort()
a

array([0.06005918, 0.06772412, 0.13692016, 0.16822173, 0.31569647,
       0.36072102, 0.37377919, 0.64277145, 0.68118616, 0.76203523])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [9]:
a = np.random.randint(1, 10, 5)
print(a)
np.add.reduce(a)

[4 5 7 3 8]


np.int64(27)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [13]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

eq1 = np.allclose(A,B)
eq2 = np.array_equal(A,B)

print(A, B)
print(eq1, eq2)

[0 0 0 1 0] [0 0 0 1 0]
True True


In [4]:
answer(42)

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)


#### 43. Make an array immutable (read-only) (★★☆)

In [16]:
a = np.arange(1, 11)
a.flags.writeable = False
print(a)
a[4] = 0

[ 1  2  3  4  5  6  7  8  9 10]


ValueError: assignment destination is read-only

In [15]:
answer(43)

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [2]:
a = np.random.uniform(1, 101, size = (10, 2))

r = np.sqrt(a[:, 0]**2 + a[:, 1]**2)
theta = np.arctan2(a[:, 1], a[:, 0])
a[:, 0] = r
a[:, 1] = theta
print(a)

[[3.07283092e+01 6.68719840e-01]
 [4.05865535e+01 7.72516925e-01]
 [7.42914760e+01 8.54558621e-02]
 [2.30269080e+01 5.09866302e-01]
 [6.96956520e+01 1.42368944e+00]
 [6.06898259e+01 9.21926627e-01]
 [7.09417019e+01 1.31968632e+00]
 [1.26344411e+02 6.72903539e-01]
 [8.05929337e+01 1.17613131e+00]
 [4.37556547e+01 1.18466183e+00]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [23]:
a = np.random.randint(1, 11, size = (10))
print(a)
a[a == a.max()] = 0
print(a)

[3 8 7 7 9 2 7 7 9 6]
[3 8 7 7 0 2 7 7 0 6]


In [18]:
a = np.random.randint(1, 11, size = (10))
print(a)
a[a.argmax()] = 0
print(a)

[ 2 10  2  1 10  8  7 10  3  2]
[ 2  0  2  1 10  8  7 10  3  2]


In [10]:
hint(45)

hint: argmax


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [29]:
Z = np.zeros((5,5), [('x',float),('y',float)])
print(Z)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]


In [30]:
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [27]:
answer(46)

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
x = np.random.randint(1, 11, [('x', int), ('y', int)], size = 5)
y = np.random.randint(21, 31, (6))
c = np.zeros((5,6))
c = 

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [55]:
k = 10
a = np.abs(np.array([1, 2, 5, 3, 6, 6, 4]) - k)
a.min() + k

np.int64(14)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)